[project]
name = "atlassian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.5"
dependencies = [
    "fastmcp>=2.2.0",
    "mcp[cli]>=1.6.0",
]
